name: Generate NPM lock files
on:
  schedule:
    - cron: 0 8 * * *
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-lockfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        name: Install Nix
        with:
          install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          nix_path: https://github.com/NixOS/nixpkgs/archive/08ef0f28e3a41424b92ba1d203de64257a9fca6a.tar.gz
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Update Inputs
        run: nix flake update
      - name: Generate lock files
        run: |
          nix develop -c ./scripts/make_lockfiles
      - uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:
          add: "['js/packages/cli/package-lock.json', 'js/packages/fair-launch/package-lock.json',  'js/packages/web/package-lock.json', 'flake.lock']"
          default_author: github_actor
          message: 'Committed updated package-lock.json and flake.lock files'
